name: "COS Builder"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the depot_tools
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
