name: "COS Builder"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the depot_tools
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH

      - name: Init and sync repo
        working-directory: cos-src
        run: |
          repo init -u https://cos.googlesource.com/cos/manifest.git --repo-url https://chromium.googlesource.com/external/repo.git
          repo sync
          ls

