name: "COS Builder"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the depot_tools
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
          mkdir -p cos-src

      - name: Init and sync repo
        working-directory: cos-src
        run: |
          repo init -u https://cos.googlesource.com/cos/manifest.git --repo-url https://chromium.googlesource.com/external/repo.git
          repo sync
          ls

      - name: Chroot and build
        working-directory: cos-src
        run: |
          cros_sdk --enter -- "./build_packages --board=lakitu; ./build_image --board=lakitu base"
          ls

      - name: Archive cos image
        uses: actions/upload-artifact@v2
        with:
          name: cos-image
          path: cos-src/src/build/images/lakitu/latest/

